name: Hello World (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted
    
    steps:
      - name: Verification du runner
        run: echo "Runer actif sur $(hostname)"
        
      - name: Hello World
        run: echo "Hello World depuis le runner self-hosted"